---

- name: Distribute CA to nodes
  copy:
    src: "{{ elasticsearch_local_cert_dir }}/{{ elasticsearch_ca_cert_name }}"
    dest: "{{ elasticsearch_directories.certs_dir }}/{{ elasticsearch_ca_cert_name }}"
    mode: '0644'
    owner: "{{ elasticsearch_elastic_user }}"
    group: "{{ elasticsearch_elastic_group }}"

- name: Distribute pre-signed certs to remote hosts
  copy:
    src: "{{ elasticsearch_local_cert_dir }}/{{ elasticsearch_cert_name }}"
    dest: "{{ elasticsearch_directories.certs_dir }}/{{ elasticsearch_cert_name }}"
    owner: "{{ elasticsearch_elastic_user }}"
    group: "{{ elasticsearch_elastic_group }}"
    mode: '0764'

- name: Distribute pre-signed keys to remote hosts
  copy:
    src: "{{ elasticsearch_local_cert_dir }}/{{ elasticsearch_key_name }}"
    dest: "{{ elasticsearch_directories.certs_dir }}/{{ elasticsearch_key_name }}"
    owner: "{{ elasticsearch_elastic_user }}"
    group: "{{ elasticsearch_elastic_group }}"
    mode: '0764'
